// Mocks generated by Mockito 5.4.6 from annotations
// in fitness/test/features/auth/forgot_password/data/data_sources/remote/reset_password_remote_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:fitness/core/api_manager/api_manager.dart' as _i6;
import 'package:fitness/features/auth/forgot_password/data/models/request/reset_password_request_model.dart'
    as _i10;
import 'package:fitness/features/auth/forgot_password/data/models/request/send_email_request_model.dart'
    as _i8;
import 'package:fitness/features/auth/forgot_password/data/models/request/verify_reset_code_request_model.dart'
    as _i9;
import 'package:fitness/features/auth/forgot_password/data/models/response/reset_password_response_model.dart'
    as _i4;
import 'package:fitness/features/auth/forgot_password/data/models/response/send_email_response_model.dart'
    as _i2;
import 'package:fitness/features/auth/forgot_password/data/models/response/verify_reset_code_response_model.dart'
    as _i3;
import 'package:fitness/features/auth/login/data/model/login_user_dto.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSendEmailResponseModel_0 extends _i1.SmartFake
    implements _i2.SendEmailResponseModel {
  _FakeSendEmailResponseModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVerifyResetCodeResponseModel_1 extends _i1.SmartFake
    implements _i3.VerifyResetCodeResponseModel {
  _FakeVerifyResetCodeResponseModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeResetPasswordResponseModel_2 extends _i1.SmartFake
    implements _i4.ResetPasswordResponseModel {
  _FakeResetPasswordResponseModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResponse_3 extends _i1.SmartFake implements _i5.LoginResponse {
  _FakeLoginResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RestClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestClient extends _i1.Mock implements _i6.RestClient {
  MockRestClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.SendEmailResponseModel> sendEmail(
    _i8.SendEmailRequestModel? requestModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendEmail, [requestModel]),
            returnValue: _i7.Future<_i2.SendEmailResponseModel>.value(
              _FakeSendEmailResponseModel_0(
                this,
                Invocation.method(#sendEmail, [requestModel]),
              ),
            ),
          )
          as _i7.Future<_i2.SendEmailResponseModel>);

  @override
  _i7.Future<_i3.VerifyResetCodeResponseModel> verifyCode(
    _i9.VerifyResetCodeRequestModel? requestModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyCode, [requestModel]),
            returnValue: _i7.Future<_i3.VerifyResetCodeResponseModel>.value(
              _FakeVerifyResetCodeResponseModel_1(
                this,
                Invocation.method(#verifyCode, [requestModel]),
              ),
            ),
          )
          as _i7.Future<_i3.VerifyResetCodeResponseModel>);

  @override
  _i7.Future<_i4.ResetPasswordResponseModel> resetPassword(
    _i10.ResetPasswordRequestModel? requestModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [requestModel]),
            returnValue: _i7.Future<_i4.ResetPasswordResponseModel>.value(
              _FakeResetPasswordResponseModel_2(
                this,
                Invocation.method(#resetPassword, [requestModel]),
              ),
            ),
          )
          as _i7.Future<_i4.ResetPasswordResponseModel>);

  @override
  _i7.Future<_i5.LoginResponse> login(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#login, [map]),
            returnValue: _i7.Future<_i5.LoginResponse>.value(
              _FakeLoginResponse_3(this, Invocation.method(#login, [map])),
            ),
          )
          as _i7.Future<_i5.LoginResponse>);
}
